"""error handling

Revision ID: 9fea97d24a89
Revises: 4a547d2d168c
Create Date: 2024-08-26 11:42:20.372877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fea97d24a89'
down_revision = '4a547d2d168c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('popularity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'popularity_score')
    # ### end Alembic commands ###
